import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/style.css" />
        <script src="/common.js" defer></script>
      </head>

      <body className={inter.className}>
        <Navbar />
        {children}</body>
    </html>
  )
}

const Navbar = () => {
  const li_style = 'mx-4';
  return (
    <nav >
      <ul className='flex p-4 justify-center shadow' >
        <li className={li_style}><Link href={'/'}>Home</Link></li>
      </ul>
    </nav>
  )
}